### PR TITLE
Remove short-circuiting added for wasm bindgen bug

### LINKED ISSUE #1181: Remove short-circuiting added for wasm bindgen bug
For all changes introduced as part of https://github.com/Plutonomicon/cardano-transaction-lib/issues/875, namely [these](https://github.com/Plutonomicon/cardano-transaction-lib/pull/1025), restore the old behavior.

Blocked by #1170 to be merged.

### PR DESCRIPTION
**Pull request by rynoV**
Closes #1181.

All tests are passing locally. I also ran the reproduction code provided in #875 and confirmed memory access issue no longer occurs.

### Pre-review checklist

- [x] All code has been formatted using our config (`make format`)
- [x] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [x] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

### CODE REVIEW

**Comment by rynoV** [comment]
@klntsky #1025 also [removed `newBigNum`](https://github.com/Plutonomicon/cardano-transaction-lib/pull/1025/files#diff-1ea2f5572ca353f84fb1ae81510ffcba64a8d69c1a063ae7b207de5d9146edbfL14-L21), I wasn't sure if we wanted to add that back here. It doesn't appear to be needed.

**Review by pb99u069 — APPROVED** [review]

File: src/Internal/Types/BigNum.js [hunk 1]
```diff
@@ -13,66 +13,27 @@ exports.zero = lib.BigNum.zero();
...
     return maybe.nothing;
   }
 };
 
 exports._fromString = maybe => str => {
-  // this is needed because try/catch overuse breaks runtime badly
-  // https://github.com/Plutonomicon/cardano-transaction-lib/issues/875
+  if (str[0] == "-") {
+    return maybe.nothing;
+  }
```
Comment (klntsky) [inline src/Internal/Types/BigNum.js:35]: This check is not needed as well. It was added for the same reason, just before this PR.

**Review by klntsky — CHANGES_REQUESTED** [review]

**Review by klntsky — APPROVED** [review]
